Algoritmo "Estrutura-de-repetição "
// Professor   : Antonio Carlos Nicolodi 
// Data atual  : 21/10/2022
Var

   contador : inteiro
Inicio
      contador <- 0
      Escreval("Vou contar até 10")
      Enquanto (contador <= 10) faca
               Escreval(contador)
               contador <- contador + 1
      FimEnquanto
      Escreval("Terminei de contar.")
Fimalgoritmo
//Estruturas de repetição