Algoritmo "Estrutura-de-repetição-ex02 "
// Professor   : Antonio Carlos Nicolodi
// Data atual  : 21/10/2022
Var

   contador : inteiro
   Numero : inteiro
Inicio
      contador <- 0
      Escreval("Digite um numero: ")
      Leia(Numero)
      Enquanto (contador <= numero) faca
               Escreval(contador)
               contador <- contador + 1
      FimEnquanto
      Escreval("Terminei de contar.")
Fimalgoritmo
//Estruturas de repetição