Algoritmo "FazSoma"
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/11/2022
Var

   X, Y: Inteiro
Procedimento Soma(A, B: Inteiro)
inicio
      Escreval("Recebi o valor ",A)
      Escreval("Recebi o valor ",B)
      Escreval("A soma entre os dois e ",A + B)
FimProcedimento
Inicio
      Escreval("Digite um valor: ")
      Leia(X)
      Escreval("Digite outro valor: ")
      Leia(Y)
      Soma (X, Y)
Fimalgoritmo