Algoritmo "Variaveis-Compostas-homogeneas-unidimensionais"
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/11/2022
Var
   V: vetor[1..6] de Inteiro // Variavel composta
   C: Inteiro
Inicio
      Para C <- 1 ate 6 faca
           Escreval("Digite o ", C,"o, valor: ")
           Leia(V[C])
      FimPara
Fimalgoritmo
//Variaveis compostas é como armazenar mais de um valor em uma mesma variavel
//Explicação "Variaveis compostas DE VARIOS ESPAÇOS" HOMOGENIAS = todas do msm tipo